Various fixes

diff --git a/bash-template b/bash-template
--- a/bash-template
+++ b/bash-template
@@ -9,13 +9,13 @@ scriptDirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 # temp directory
 tempDirectory=$(mktemp -d -t tmp.XXXXXXXXXX)
 function cleanup {
-  rm -rf "$tempDirectory"
+    rm -rf "$tempDirectory"
 }
 trap cleanup EXIT
 
 # arguments parsing
-OPTIONS=hp
-LONGOPTS=help,parameters
+OPTIONS=hpt
+LONGOPTS=help,parameters,temporary
 
 parameters="false"
 temporary="false"
@@ -29,14 +29,18 @@ eval set -- "$PARSED"
 while true; do
     case "$1" in
         -h|--help)
-			echo "<command description>"
-			echo "$0 [<optional arguments>] <required arguments>"
-			echo ""
-			echo "-p|--parameters - add parameter parsing logic"
-			exit 1
+            echo "<command description>"
+            echo "$0 [<optional arguments>] <required arguments>"
+            echo ""
+            echo "-p|--parameters - add parameter parsing logic"
+            exit 1
             ;;
         -p|--parameters)
-			parameters="true"
+            parameters="true"
+            shift
+            ;;
+        -t|--temporary)
+            temporary="true"
             shift
             ;;
         --)
@@ -52,8 +56,8 @@ done
 
 # handle non-option arguments
 if [[ $# -ne 0 ]]; then
-	echo ""
-	echo "Use -h to see more info"
+    echo ""
+    echo "Use -h to see more info"
     exit 4
 fi
 
@@ -64,5 +68,5 @@ if [[ "$temporary" == "true" ]]; then
 fi
 
 if [[ "$parameters" == "true" ]]; then
-	cat "$scriptDirectory/bash-template-parameters.sh"
+    cat "$scriptDirectory/bash-template-parameters.sh"
 fi
diff --git a/kube-wireshark b/kube-wireshark
--- a/kube-wireshark
+++ b/kube-wireshark
@@ -1,10 +1,82 @@
 #!/bin/bash
 
-set -e
+# More safety, by turning some bugs into errors.
+set -euCo pipefail
+IFS=$'\n\t'
 
-expression="$1"
+scriptDirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 
-host="$2"
+
+printHelp() {
+	echo "Capture traffic from Kubernetes cluster and forard it to local Wireshark"
+	echo "$0 [-e <expression> ] <host>"
+	echo ""
+	echo "-e|--expression <expression> - tcpdump like expression to filter traffic"
+}
+
+# default values
+expression="not port 22"
+pod=""
+
+# arguments parsing
+OPTIONS=he:p:
+LONGOPTS=help,expression:,host:,pod:
+
+! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
+if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+    exit 2
+fi
+eval set -- "$PARSED"
+
+while true; do
+    case "$1" in
+        -h|--help)
+			printHelp
+			exit 1
+            ;;
+        -e|--expression)
+            expression="$2"
+            shift 2
+            ;;
+		-p|--pod)
+			pod="$2"
+			shift 2
+			;;
+		--host)
+			host="$2"
+			shift 2
+			;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "Programming error"
+            exit 3
+            ;;
+    esac
+done
+
+# handle non-option arguments
+if [[ $# -ne 0 ]]; then
+	echo "Error: Arguments required"
+	echo ""
+	printHelp
+    exit 4
+fi
+
+if (( $# > 0 )); then
+	expression="$1"
+fi
+
+if [[ -n "$pod" ]]; then
+	# catch traffic from pod
+	kubectl debug -i --image corfr/tcpdump "$pod" -c "tcpdump-$RANDOM" -- tcpdump -i any -w - "$expression" #| wireshark -k -i -
+	exit
+fi
+
+
+# catch traffic on host
 
 json='
 {
